sudo: required
language: bash
services:
- docker
script:
- sh build.sh
deploy:
  provider: s3
  access_key_id:
    secure: RY4Ibctdr/020yuDcghXzcgBuwLVfBZbRUD6d5GkUHLIRSoV0Ylww8IKHg7nZRFoI5HcqhXB5jAEf/MDEKDddnqBLyJDapqohxk2lHe3tkTe42dyfoRz6bIKqoTWgtxTu7mZNILYZ8hba5ENLhGHKUszbIphCIXBnDhmBO9Hjcomv8YNG0zIiCJZ/ZD6vRaehHDfIVJZVHw8z00pfyByNbWCsJIME4/+NAXKbqjyddlV/5OXdeyP5/YuRTT1S72uFK8DfQ54gJkV/j/afhFPs5HP5KEFNUAldYSz0ADq0EWXSKXIhwjzibTtMN8nF8R7kIJu5LRMCwKZxNP05vSl7ZJbUKP3El9lTzydDGES/u/9YW++u6ff6vHo8wcJ04znU6rB9n5CurqKkRu49pY2uJhNFCJm9JJROotwOpddCyAuB1UVehTZj8qfezIG7aDdBtdS6ASGSIQms0+9S2k0gf+T16WZijQ8h3ksqEj4Cd6Nkx8X7uuFUJl+oBXt/ZQXIpx/0smQw2C6SX8aWH6ULh8The2HSkA8oeVb5InM3nRlifn/QFvXlXFtGo5TcTLc50p3goHufOlNfNoTYqen55vpsoELB918zrC7ZjfG/4pPEDFhkJOMfSacfrGuQ3Ecrebu9yI7CKwUzp/9YF2OJnoxA/fAw4mmkFLwl3/bI1E=
  secret_access_key:
    secure: J8fFryEMB3t1QxafOLoZpDpKRmpJWDESq525l6Ozdvy8rrhz6bIxRGZYgLe8mbciZWaSgYo4MM/k1ovWm/ibidmibmLDcRt+QQqezBYLBDg6Gs13Yn6kgdjEvIFxEeAYNcxax0fGBPZnaKAMgGx9XP4bwWuNxEoZKDrC/HcQE8qifmnXFPUw+pIcseTnb5fqAIZfu1IM9QXNgHYjUP1zW9C7A3DtzoJgNtkuB/DkPp6QxkEoro0AufHOKD1Dli2z8D9wDvZWNIWndyjchbmCzk7FrBrUKFkbAi6EeSU6ZSEa7Hn0maQU1YZhuZANp5LXnxxq5SlcVjF9FhyV6O+A+I1TnNu9gmww7gfS0ZSwp2b/6j2d92/BKRp1J+64jpPXSjfAIstbIJQWSCfd0fogwIFjpzZ0/z86dngmMKJJcA4HXA73NypBhh0CVDBkK1lYFl5s095OPLTZ9qNSJjYaXm7k45fy9o+NhPXDdLECog+72vKd89sCTnFt57LHHP32lYD6WBNDrx3W/e2Tn5jlvhKj7p9T5PHfbKEPquetj9NgZkjCleJ4X9QoUOg2jO0ctwu2OGOwVRTIz/gAK6NIOvGaY3RocmkvPcoY4xJz9xQv9/Og50qkPK9mpuY1g/zwGIBc72doDSOp90h8G5/zhEiMPgp4FNUlCwybmIIaN8s=
  bucket:
    secure: EAgTO20zL9U3GO9KdeiAg8Tz4V0NMr8lh+cZi/lwChqi09/cgxcx15cjkKEdx2UifxSDHLRzm/wp+NmGqCrKMV7Od270uIYgtMkn7RSfWO3g3FH8lVvx+cYKUcPjirEFM4jz6e6UtuCRx0Uy+pS2Jn3g6/OELoO7LsYgVCvVnTybAoZtwEHzg9/tbwT+K63pUbHl3LI+Qp1Fn/DPMTpwH4GlVprJ59uBKmRoWZBV/4FkElUFadwg9ZqOXR5+r4lDxB/RCb3Qa7fDFt2xKvc4jaxk+EVaWKDraGkBim3B7e4E0ymcIQ2CRQBE/+KpNrWbtqBL+rxmk6X/uOQ1cc+X3+ZlCQ0icpPB2PojR5U0lHqoEIu8s7ltv0rnfRxF8U6X//JpaSpJ+z6b8ZAmfmWLLducDI7HN2UbR370rwnCkfSHAUX8Cu2X0GREn5JYjvGFSSDck9DxfA+7seJcUmjGfJUnP/clbYsuoQrFCvkSNBoV1buLh1sgjCwwlqX8PDGAER3dA3K0hnAYdd22VS+1Am1YlILO4/+z/j4rD3576vZwc5N8HajQWX2u0afs7IUh1XSeBwZPL/OltZv8njNkNY4FVCbZfZYJUU9RPf4IhIgysu5qU8p0N5luRMzfMVwSk79XSnhdXd4npxho2JO75G3HZOnijK7F43o6sQ09MWs=
  region: eu-west-1
  local-dir: target/site
  upload-dir: poacc/upgrade-3
  acl: public_read
  skip_cleanup: true
  on:
    repo: OpenPEPPOL/poacc-upgrade-3
    branch: master
